# Generated by Django 5.1.4 on 2025-01-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_num",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("question", models.TextField(unique=True)),
                ("author", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["question_num"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        unique=True,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_questions",
                        to="quizApp.question",
                    ),
                ),
            ],
        ),
    ]
