# Generated by Django 5.1.4 on 2025-01-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="answer_to_question",
            field=models.TextField(default="your answer", unique=True),
        ),
    ]
