# Generated by Django 5.1.4 on 2025-01-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizApp.quiz",
            ),
        ),
    ]
