# Generated by Django 5.1.4 on 2025-01-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0002_choice_answer_to_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ["choice"]},
        ),
        migrations.AlterModelTable(
            name="choice",
            table="choices",
        ),
    ]
