# Generated by Django 5.1.4 on 2025-01-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0003_alter_choice_options_alter_choice_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
            ),
        ),
    ]
