# Generated by Django 5.1.4 on 2025-01-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0004_alter_choice_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ["question", "choice"]},
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                default="{question.question}",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_questions",
                to="quizApp.question",
            ),
        ),
    ]
