# Generated by Django 5.1.5 on 2025-01-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0005_quizsession_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
