# Generated by Django 5.1.5 on 2025-01-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0008_remove_score_quiz_name_score_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="quiz",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizApp.quiz",
            ),
        ),
    ]
