# Generated by Django 5.1.5 on 2025-01-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0009_useranswer_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
