# Generated by Django 5.1.5 on 2025-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0011_userprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time",
            field=models.IntegerField(
                default="1", help_text="Duration of the quiz in seconds"
            ),
        ),
    ]
