# Generated by Django 5.1.5 on 2025-01-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0012_quiz_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="number_of_questions",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizApp.quiz"
            ),
        ),
    ]
