# Generated by Django 5.1.5 on 2025-01-25 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0013_quiz_number_of_questions_alter_question_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                default="{question.question}",
                on_delete=django.db.models.deletion.CASCADE,
                to="quizApp.question",
            ),
        ),
    ]
