# Generated by Django 5.1.5 on 2025-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0014_alter_choice_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="time",
            field=models.IntegerField(
                default="120", help_text="Duration of the quiz in seconds"
            ),
        ),
    ]
