# Generated by Django 5.1.5 on 2025-01-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0015_alter_quiz_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together=set(),
        ),
    ]
