# Generated by Django 5.1.5 on 2025-01-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0016_alter_useranswer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizApp.question"
            ),
        ),
    ]
